function [alphaMax, omega] = getAlphaMax(N, paramArray, alphaLeft, alphaRight, ...
    u0__x_vec, du0x_dxi_vec, d2u0x_dxidxi_vec,...
        rho0_vec, drho0_dxi_vec, d2rho0_dxidxi_vec,...
        T0_vec, dT0_dxi_vec, d2T0_dxidxi_vec, ...
        Y0_vec, dY0_dxi_vec, d2Y0_dxidxi_vec, ...
        D12_vec, dD_dT_vec, dD_drho_vec, dD_dY_vec, d2D_dTdT_vec, d2D_dTdrho_vec, d2D_dTdY_vec, d2D_drhodrho_vec, d2D_drhodY_vec, d2D_dYdY_vec,...
        mu_vec, dmu_dT_vec, dmu_drho_vec, dmu_dY_vec, d2mu_dTdT_vec, d2mu_dTdrho_vec, d2mu_dTdY_vec, d2mu_drhodrho_vec, d2mu_drhodY_vec, d2mu_dYdY_vec, ...
        P_vec, dp_dT_vec, dp_drho_vec, dp_dY_vec, d2p_dTdT_vec, d2p_dTdrho_vec, d2p_dTdY_vec, d2p_drhodrho_vec, d2p_drhodY_vec, d2p_dYdY_vec, ...
        h_vec, dh_dT_vec, dh_drho_vec, dh_dY_vec,...
        lambda_vec, dlambda_dT_vec, dlambda_drho_vec, dlambda_dY_vec, d2lambda_dTdT_vec, d2lambda_dTdrho_vec, d2lambda_dTdY_vec, d2lambda_drhodrho_vec, d2lambda_drhodY_vec, d2lambda_dYdY_vec)
    % Initial Step

    omegaLeft = getUnstableOmega(alphaLeft, N, paramArray, ...
        u0__x_vec, du0x_dxi_vec, d2u0x_dxidxi_vec,...
        rho0_vec, drho0_dxi_vec, d2rho0_dxidxi_vec,...
        T0_vec, dT0_dxi_vec, d2T0_dxidxi_vec, ...
        Y0_vec, dY0_dxi_vec, d2Y0_dxidxi_vec, ...
        D12_vec, dD_dT_vec, dD_drho_vec, dD_dY_vec, d2D_dTdT_vec, d2D_dTdrho_vec, d2D_dTdY_vec, d2D_drhodrho_vec, d2D_drhodY_vec, d2D_dYdY_vec,...
        mu_vec, dmu_dT_vec, dmu_drho_vec, dmu_dY_vec, d2mu_dTdT_vec, d2mu_dTdrho_vec, d2mu_dTdY_vec, d2mu_drhodrho_vec, d2mu_drhodY_vec, d2mu_dYdY_vec, ...
        P_vec, dp_dT_vec, dp_drho_vec, dp_dY_vec, d2p_dTdT_vec, d2p_dTdrho_vec, d2p_dTdY_vec, d2p_drhodrho_vec, d2p_drhodY_vec, d2p_dYdY_vec, ...
        h_vec, dh_dT_vec, dh_drho_vec, dh_dY_vec,...
        lambda_vec, dlambda_dT_vec, dlambda_drho_vec, dlambda_dY_vec, d2lambda_dTdT_vec, d2lambda_dTdrho_vec, d2lambda_dTdY_vec, d2lambda_drhodrho_vec, d2lambda_drhodY_vec, d2lambda_dYdY_vec);
    omegaRight= getUnstableOmega(alphaRight, N, paramArray, ...
        u0__x_vec, du0x_dxi_vec, d2u0x_dxidxi_vec,...
        rho0_vec, drho0_dxi_vec, d2rho0_dxidxi_vec,...
        T0_vec, dT0_dxi_vec, d2T0_dxidxi_vec, ...
        Y0_vec, dY0_dxi_vec, d2Y0_dxidxi_vec, ...
        D12_vec, dD_dT_vec, dD_drho_vec, dD_dY_vec, d2D_dTdT_vec, d2D_dTdrho_vec, d2D_dTdY_vec, d2D_drhodrho_vec, d2D_drhodY_vec, d2D_dYdY_vec,...
        mu_vec, dmu_dT_vec, dmu_drho_vec, dmu_dY_vec, d2mu_dTdT_vec, d2mu_dTdrho_vec, d2mu_dTdY_vec, d2mu_drhodrho_vec, d2mu_drhodY_vec, d2mu_dYdY_vec, ...
        P_vec, dp_dT_vec, dp_drho_vec, dp_dY_vec, d2p_dTdT_vec, d2p_dTdrho_vec, d2p_dTdY_vec, d2p_drhodrho_vec, d2p_drhodY_vec, d2p_dYdY_vec, ...
        h_vec, dh_dT_vec, dh_drho_vec, dh_dY_vec,...
        lambda_vec, dlambda_dT_vec, dlambda_drho_vec, dlambda_dY_vec, d2lambda_dTdT_vec, d2lambda_dTdrho_vec, d2lambda_dTdY_vec, d2lambda_drhodrho_vec, d2lambda_drhodY_vec, d2lambda_dYdY_vec);

    i = 1;
    fprintf('i = %d \n', i);
    fprintf('omegaLeft = %.4g, alphaLeft = %.4g \n', omegaLeft, alphaLeft);
    fprintf('omegaRight = %.4g, alphaRight = %.4g \n', omegaRight, alphaRight);
    
    while omegaLeft < 0
        alphaRight = alphaLeft;
        omegaRight = omegaLeft;
        
        alphaLeft = alphaLeft - 0.1;
        omegaLeft = getUnstableOmega(alphaLeft, N, paramArray, ...
            u0__x_vec, du0x_dxi_vec, d2u0x_dxidxi_vec,...
        rho0_vec, drho0_dxi_vec, d2rho0_dxidxi_vec,...
        T0_vec, dT0_dxi_vec, d2T0_dxidxi_vec, ...
        Y0_vec, dY0_dxi_vec, d2Y0_dxidxi_vec, ...
        D12_vec, dD_dT_vec, dD_drho_vec, dD_dY_vec, d2D_dTdT_vec, d2D_dTdrho_vec, d2D_dTdY_vec, d2D_drhodrho_vec, d2D_drhodY_vec, d2D_dYdY_vec,...
        mu_vec, dmu_dT_vec, dmu_drho_vec, dmu_dY_vec, d2mu_dTdT_vec, d2mu_dTdrho_vec, d2mu_dTdY_vec, d2mu_drhodrho_vec, d2mu_drhodY_vec, d2mu_dYdY_vec, ...
        P_vec, dp_dT_vec, dp_drho_vec, dp_dY_vec, d2p_dTdT_vec, d2p_dTdrho_vec, d2p_dTdY_vec, d2p_drhodrho_vec, d2p_drhodY_vec, d2p_dYdY_vec, ...
        h_vec, dh_dT_vec, dh_drho_vec, dh_dY_vec,...
        lambda_vec, dlambda_dT_vec, dlambda_drho_vec, dlambda_dY_vec, d2lambda_dTdT_vec, d2lambda_dTdrho_vec, d2lambda_dTdY_vec, d2lambda_drhodrho_vec, d2lambda_drhodY_vec, d2lambda_dYdY_vec);
        
        i = i+1;
        fprintf('i = %d \n', i);
        fprintf('omegaLeft = %.4g, alphaLeft = %.4g \n', omegaLeft, alphaLeft);
        fprintf('omegaRight = %.4g, alphaRight = %.4g \n', omegaRight, alphaRight);
    end

    while omegaRight > 0 && omegaLeft > 1e-4
        alpha = alphaLeft - omegaLeft / (omegaRight - omegaLeft) * (alphaRight - alphaLeft);
        omega = getUnstableOmega(alpha, N, paramArray, ...
            u0__x_vec, du0x_dxi_vec, d2u0x_dxidxi_vec,...
        rho0_vec, drho0_dxi_vec, d2rho0_dxidxi_vec,...
        T0_vec, dT0_dxi_vec, d2T0_dxidxi_vec, ...
        Y0_vec, dY0_dxi_vec, d2Y0_dxidxi_vec, ...
        D12_vec, dD_dT_vec, dD_drho_vec, dD_dY_vec, d2D_dTdT_vec, d2D_dTdrho_vec, d2D_dTdY_vec, d2D_drhodrho_vec, d2D_drhodY_vec, d2D_dYdY_vec,...
        mu_vec, dmu_dT_vec, dmu_drho_vec, dmu_dY_vec, d2mu_dTdT_vec, d2mu_dTdrho_vec, d2mu_dTdY_vec, d2mu_drhodrho_vec, d2mu_drhodY_vec, d2mu_dYdY_vec, ...
        P_vec, dp_dT_vec, dp_drho_vec, dp_dY_vec, d2p_dTdT_vec, d2p_dTdrho_vec, d2p_dTdY_vec, d2p_drhodrho_vec, d2p_drhodY_vec, d2p_dYdY_vec, ...
        h_vec, dh_dT_vec, dh_drho_vec, dh_dY_vec,...
        lambda_vec, dlambda_dT_vec, dlambda_drho_vec, dlambda_dY_vec, d2lambda_dTdT_vec, d2lambda_dTdrho_vec, d2lambda_dTdY_vec, d2lambda_drhodrho_vec, d2lambda_drhodY_vec, d2lambda_dYdY_vec);

        alphaLeft = alphaRight;
        omegaLeft = omegaRight;

        alphaRight = alpha;
        omegaRight = omega;

        i = i+1;
        fprintf('i = %d \n', i);
        fprintf('omegaLeft = %.4g, alphaLeft = %.4g \n', omegaLeft, alphaLeft);
        fprintf('omegaRight = %.4g, alphaRight = %.4g \n', omegaRight, alphaRight);
    end


    % Bisect
    while omegaLeft > 1e-4
        alpha = (alphaLeft + alphaRight) / 2;
        omega = getUnstableOmega(alpha, N, paramArray, ...
            u0__x_vec, du0x_dxi_vec, d2u0x_dxidxi_vec,...
        rho0_vec, drho0_dxi_vec, d2rho0_dxidxi_vec,...
        T0_vec, dT0_dxi_vec, d2T0_dxidxi_vec, ...
        Y0_vec, dY0_dxi_vec, d2Y0_dxidxi_vec, ...
        D12_vec, dD_dT_vec, dD_drho_vec, dD_dY_vec, d2D_dTdT_vec, d2D_dTdrho_vec, d2D_dTdY_vec, d2D_drhodrho_vec, d2D_drhodY_vec, d2D_dYdY_vec,...
        mu_vec, dmu_dT_vec, dmu_drho_vec, dmu_dY_vec, d2mu_dTdT_vec, d2mu_dTdrho_vec, d2mu_dTdY_vec, d2mu_drhodrho_vec, d2mu_drhodY_vec, d2mu_dYdY_vec, ...
        P_vec, dp_dT_vec, dp_drho_vec, dp_dY_vec, d2p_dTdT_vec, d2p_dTdrho_vec, d2p_dTdY_vec, d2p_drhodrho_vec, d2p_drhodY_vec, d2p_dYdY_vec, ...
        h_vec, dh_dT_vec, dh_drho_vec, dh_dY_vec,...
        lambda_vec, dlambda_dT_vec, dlambda_drho_vec, dlambda_dY_vec, d2lambda_dTdT_vec, d2lambda_dTdrho_vec, d2lambda_dTdY_vec, d2lambda_drhodrho_vec, d2lambda_drhodY_vec, d2lambda_dYdY_vec);

        if omega > 0
            alphaLeft = alpha;
            omegaLeft = omega;
        else
            alphaRight = alpha;
            omegaRight = omega;
        end
        i = i+1;
        fprintf('i = %d \n', i);
        fprintf('omegaLeft = %.4g, alphaLeft = %.4g \n', omegaLeft, alphaLeft);
        fprintf('omegaRight = %.4g, alphaRight = %.4g \n', omegaRight, alphaRight);
    end
    
    alphaMax = alphaLeft;
    omega = omegaLeft;
    assert(omega > 0)
    
end

